app:
  properties:
    message: Welcome To Ashok IT School From QA
    db-uname: iesapp-qa
    db-pwd: ies@123
    db-driver-class: oracle.jdbc.driver.OracleDriver
    db-url: jdbc:oracle:thin:@localhost:1522/XE
server:
  port: 9090